global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: mysql-exporter
    static_configs:
      - targets: ["mysql-exporter:9104"]
  - job_name: node-exporter
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: store-service
    static_configs:
      - targets: ["store-service:8000"]
